version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  webserver:
    build: .
    container_name: airflow_webserver
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: 'P8v9Ga-DV6F_0cufY3X3H1S-62pfGACWXhIvMT-0pUY='
      AIRFLOW__WEBSERVER__SECRET_KEY: '83d7fe87d25162302074ebfecac321e04003453c54284ad6'
    command: webserver
    restart: always

  scheduler:
    build: .
    container_name: airflow_scheduler
    depends_on:
      - webserver
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: 'P8v9Ga-DV6F_0cufY3X3H1S-62pfGACWXhIvMT-0pUY='
    command: scheduler
    restart: always

volumes:
  postgres_data:
